version: "3"
services:
      client-app:
            container_name: client-app
            build: ./client-app
            ports:
              - 3000:3000
            volumes:
              - ./client-app/src:/app/src:ro
      api-server:
            container_name: api-server
            build: ./api-server
            ports:
              - 8000:8000


